### ISSUE TITLE
full screen doesn't align with gui ?

### ISSUE THREAD

**Issue by heyitsalina** [heyitsalina/ant_search_algorithm#107]
<img width="1439" alt="Bildschirmfoto 2024-02-07 um 14 15 59" src="https://github.com/heyitsalina/ant_search_algorithm/assets/146937991/1166a5a2-c1e1-4e21-9f89-2fd83c0beb23">

hey guys, i just tried running the gui on my laptop and when running the command, the gui automatically opens up as a full screen - tab and looks a bit wonky because of the false realignment with my screen.
to be fair, i think it isn't that big of a problem since we typically only use a small tab when opening the gui, is there a specific reason behind this? i thought that it maybe has something to do with the shape, pixel size (?) or the center of the gui for which we used kivy, that makes it intentional to use only as a small tab instead of having your full screen.
it might also be possible that this "problem" is a macbook-user-only thing, as per usual :I
Maybe i've just missed a crucial info when it comes to the gui and the full screen, my apologies if that is the case! 😪

however, an explanation would still be appreciated, thought i'd ask before jumping to conclusions by myself ☺️

**Comment by Jonah-gr** [comment]
I think this is due to the resolution of your laptop. At the moment the background only works properly for FullHD screens.
I can easily adjust that :)
