### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by honnigmelone** [heyitsalina/ant_search_algorithm#117]
This one is a hard one to do just like that, but we should still create this as an issue. 
So following the completion of our base code (like the docstring issue #53), we should prioritize looking if we can add some clean code practices.

This should enhance our overall code quality :)

**Comment by Jonah-gr** [comment]
> @Jonah-gr: Is it possible to move the methods `find_pheromone_trace()` and `get_pheromone_position()` from the Simulation class to the Pheromone class?

I will try it.

**Comment by AlhaririAnas** [comment]
> I will try it.

It was actually just a question, but thanks for trying 😄

**Comment by tis22** [comment]
Is "partly" solved by #148.
Cleaning is generally always possible! 😉
