### ISSUE TITLE
Test for GUI

### ISSUE THREAD

**Issue by honnigmelone** [heyitsalina/ant_search_algorithm#122]
If we want to reach our test coverage according to assignment guidelines we need to create tests for the gui.

**Comment by Jonah-gr** [comment]
Writing tests for the gui can be quite complicated. I also clarified this at the beginning and the gui is not included in the test coverage.
But I can have a look at how to do this and implement it if possible.

**Comment by honnigmelone** [comment]
Oh I was not sure about the gui and i forgot about it. I would be fine with closing this issue again, unless you already worked on it.  Sorryyyyy for that 🐙
