### ISSUE TITLE
check position of food

### ISSUE THREAD

**Issue by AlhaririAnas** [heyitsalina/ant_search_algorithm#133]
We need to ensure that food sources aren't placed on obstacles. For this, we require a new method to check the coordinates of the food before placing it. If there's an overlap with an obstacle, the food should be placed right next to it.

Important: If an obstacle is located directly at the edge of the ant world and an overlap occurs, the food must be positioned at a free spot within the world. All four sides of the obstacle should be checked. The food should be placed on the first side where there is enough space.

![20240218-1800-09 5346226-ezgif com-video-to-gif-converter](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/d6e40fb0-ac39-4adf-95f1-ab796b9d6238)

**Comment by AlhaririAnas** [comment]
I agree that generalizing the check_for_obstacles() method to include checks for food and colonies is a feasible approach. However, for simplicity and clarity in the code, I would recommend initially creating a separate function, check_for_food().

**Comment by honnigmelone** [comment]
I don't know what happened but my gui and simulation work again. I will try this issue again.

**Comment by tis22** [comment]
I guess this is closed by #143.
