### ISSUE TITLE
Obstacle implementation

### ISSUE THREAD

**Issue by Jonah-gr** [heyitsalina/ant_search_algorithm#144]
Should we create an obstacle class so that it would be possible to set more functions and parameters there later? At the moment there are only `Image` objects from Kivy in `Simulation.obstacles`.

**Comment by honnigmelone** [comment]
I think that definitely would make sense!

**Comment by AlhaririAnas** [comment]
Yes, creating an obstacle class is a good idea as it brings structure and clarity, especially for clean code.
