### ISSUE TITLE
Create a method to display the pheromones

### ISSUE THREAD

**Issue by tis22** [heyitsalina/ant_search_algorithm#25]
In the first place the pheromons (doesn't matter if 'from colony' or 'from food') should be displayed.
Keep in mind that the two different ones should be displayed differently (e.g. color or 'from food' to be displayed and 'from colony' not to be displayed).

**Comment by heyitsalina** [comment]
additionally: create a group of pheromones and assign a value of pheromones, e.x.: if there are more pheromones in one place, it´s more likely that our lovely ants will follow that path instead of one single pheromone. 
--> they rather focus on a high concentration of pheromones and follow those

**Comment by tis22** [comment]
>  if there are more pheromones in one place, it´s more likely that our lovely ants will follow that path instead of one single pheromone

This could be displayed via the value in the array.
The values are either very strong (positive) or very weak (negative) or 0.

This could be done by a color gradient or by the opacity according to the level of the strongness/weakness.
