### ISSUE TITLE
Add 'random' Library to .toml File

### ISSUE THREAD

**Issue by AlhaririAnas** [heyitsalina/ant_search_algorithm#44]
We need to include the 'random' library in our project configuration (.toml file). The desired version for the 'random' library is 3.12.1. Please update the .toml file accordingly.

**Comment by Jonah-gr** [comment]
Random is an in-built module of Python, so we don't have to install it via pip.

**Comment by AlhaririAnas** [comment]
Okay, I didn't know that. Then it's settled.
