### ISSUE TITLE
ℹ️ Just to be informed ℹ️ 

### ISSUE THREAD

**Issue by AlhaririAnas** [heyitsalina/ant_search_algorithm#56]
Each issue is assigned a priority: High, Medium, or Low. **Please focus on High and Medium priority issues first. Only work on Low priority issues if there are no High or Medium ones left.** 

If you agree with this approach for managing our GitHub issues, please respond with an 👍

_This issue will be closed after all team members have voted._

**Comment by honnigmelone** [comment]
Yes thanks for structuring it so well ! :)

**Comment by AlhaririAnas** [comment]
@tis22 can you please read the information and agree to close this issue.

**Comment by tis22** [comment]
@AlhaririAnas Done! :)
