### ISSUE TITLE
Delete food source if food_source empty

### ISSUE THREAD

**Issue by honnigmelone** [heyitsalina/ant_search_algorithm#65]
Maybe we can implement a method that deletes a food_source from the GUI if amount_of_food reaches 0.

Maybe rather than deleting the food_source (apple) completely. The apple can be removed and a small cross or sth can be added at the center of the source indicating that there was a food source before.

<img width="116" alt="image" src="https://github.com/heyitsalina/ant_search_algorithm/assets/147641247/9435fbf8-1acd-4cb5-80d2-9f45d98e844b">

**Comment by Jonah-gr** [comment]
I'm not sure whether the food objects should simply disappear now, i.e. be deleted from the simulation.food list, or whether the images should change to crosses.

Do you think it would have advantages if the already removed food objects were marked with a cross?

**Comment by honnigmelone** [comment]
No, thinking about it again, for now, I think it is enough if they are deleted. There is not a need for the cross It was just a thought, to see where an item was. 
If we feel like it we can implement it later still.
