### ISSUE TITLE
Create tests for remaining methods in ant class

### ISSUE THREAD

**Issue by honnigmelone** [heyitsalina/ant_search_algorithm#86]
We should create unit tests for the carry_food(), try_carry_food(), drop_food() and try_drop_food().
Given the similar functionality, I think its useful to approach them together.

**Comment by tis22** [comment]
The ant-class will be updated with a few changes to the implementation of the move-method soon.
For this reason it would be a good idea to update the tests (and create new ones) for this method by the time it has been updated too.

**Comment by honnigmelone** [comment]
okay thanks for letting me know!
