### ISSUE TITLE
Implementation of a mapping-method

### ISSUE THREAD

**Issue by tis22** [heyitsalina/ant_search_algorithm#87]
As discussed in our today's meeting we need a method that maps the coordinates of the ants to the correct pheromone in the pheromone-array (in the pheromone-class).

This could be done by taking the dimensions of the world and the dimensions of the array.

Example:
If you have a width (x-axis) of 1000 and the array has 500 columns an ants position would be mapped to one element of the array, if it is in between a size of 2. By this I mean that every array-element has a "width" of 2.

$\frac{1000}{500} = 2$

- F.e. the x-coordinate of the ant is 1.5 then the ants position would be mapped to the first element of the array because this has the bounds 0 and <= 2.
- F.e. if the x-coordinate of the ant is 2 the ants position would be mapped to the second element of the array because this has the bounds 2 and <= 4.

This has to be implemented simultaneously for the x- and y-axis to ensure to map the coordinates correctly.

Vice versa this should be able to be done in both directions:
From ant-coordinates to pheromone-array-indices (row, column)
(From pheromone-array-indices (row, column) to ant-coordinates) -> I guess this is not needed because we calculate the new position via the angle (see issue #83)

**Comment by tis22** [comment]
@AlhaririAnas Please refer to this:

> (From pheromone-array-indices (row, column) to ant-coordinates) -> I guess this is not needed because we calculate the new position via the angle (see issue https://github.com/heyitsalina/ant_search_algorithm/issues/83)

Do you think we need this direction of the mapping too?

**Comment by AlhaririAnas** [comment]
@tis22 no i dont think we need it because we only need the mapped coordinates to determine where the ant is located, i.e. which pheromone index (cell) it belongs to.
