### ISSUE TITLE
Inserting the pheromone-class into the overall simulation

### ISSUE THREAD

**Issue by tis22** [heyitsalina/ant_search_algorithm#89]
We created a new class pheromones which is needed to store the pheromones of the ants.

Our teams decision was that we create an pheromone-object for each colony.
The pheromone-objects are stored in the `self.pheromones = []` in the simulation.py.

The following lines of code (simulation.py) should be included / give you an idea how the pheromone-class should do its work
(# is highlighting the new lines of code):
```python
    def next_epoch(self):
        for colony in self.colonies:
            for ant in colony.ants:
                for food in self.food:
                    if ant.try_carry_food(food):
                        ant.carry_food(food)
                        #ant.pheromone_status = 1
                        break
                if ant.try_drop_food(colony):
                    ant.drop_food(colony)
                    #ant.pheromone_status = -1

                future_position = ant.move()
                adjusted_position = self.check_future_position(future_position)
                ant.coordinates = adjusted_position
                #self.pheromone_object.leave_pheromone(ant.coordinates, ant.pheromone_status)
            #self.pheromone_object.reduce_pheromones()
        self.food = list(food for food in self.food if food.amount_of_food > 0)
```

Please update the needed parts of the gui.py so that the new class can be used.

Note: Please wait until the methods for mapping and pheromone are completely implemented to prevent further issues or ambiguities.

**Comment by Jonah-gr** [comment]
I understand, but shouldn't each colony have self.pheromones instead of the simulation so that we can correctly assign the pheromones to each colony? Otherwise we could of course use a dictionary, but I don't know if that really simplifies things.

**Comment by tis22** [comment]
Yes of course, by adding the new class into the overall simulation I meant in our code at all neccessary code-parts (I guess mainly gui.py).
