### ISSUE TITLE
Match/update coordinates arrays/kivy

### ISSUE THREAD

**Issue by tis22** [heyitsalina/ant_search_algorithm#90]
Refer to @AlhaririAnas for further instructions.

Please match/update the coordinate(s) (system) from the used arrays and the kivy-implementation.

**Comment by Jonah-gr** [comment]
What is meant by this? Why does the coordinate system of the GUI have to be changed for the implementation of the pheromones? I thought I only had to handle how the pheromones are displayed in the tensors in the GUI? Conversions have to take place for this anyway. Or what have I not understood?

**Comment by AlhaririAnas** [comment]
@Jonah-gr please see issue https://github.com/heyitsalina/ant_search_algorithm/issues/92
