### ISSUE TITLE
Shifting the coordinate system

### ISSUE THREAD

**Issue by AlhaririAnas** [heyitsalina/ant_search_algorithm#92]
Currently, the coordinate origin in the middle of the canvas. This can be problematic when adding a pheromone value at the same spot where an ant is, because the ant's position doesn't match the pheromone value's index. Therefore, it would be more practical to move the coordinate origin to the top left corner (see photo). 

Now:
![ad](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/77b98819-a182-41b9-ab0c-5cc76c318338)
After adjustment:
![ad1](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/0c45291d-5bb4-4779-a22c-91d08bf03c8e)

I've done some research and found that the `Translate()` method in the Kivy GUI library shifts the coordinate origin by a certain pixel.

**Comment by Jonah-gr** [comment]
However, conversions have to take place anyway, because there are 2 problems: 
1. kivy's (0,0) is not top left but bottom left. 
2. when increasing the x-coordniate, the next row is not used (as with arrays) but the next column.

I am currently working on an algorithm that converts this for us in both directions.

**Comment by AlhaririAnas** [comment]
> 1. kivy's (0,0) is not top left but bottom left.
Dies hatte ich auch so gedacht, aber es ist tatsächlisch wie ich erwähnt habe, der koordinatenursprung befindet sich genau in der Mitte .

![grafik](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/5de2410a-8d47-4ddf-a324-740d46559c23)

![grafik](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/d5fa412f-aa9d-47ea-a8fd-ef826994389a)

**Comment by AlhaririAnas** [comment]
> 1. kivy's (0,0) is not top left but bottom left. 

Currently, the coordinate origin (0,0) in the middle of the canvas. Take a look please! @Jonah-gr 

![grafik](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/a38fd290-c02f-494f-8834-4df0dba6da63)

![grafik](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/928af39e-6a85-4431-afd6-b617042e5ec1)

**Comment by Jonah-gr** [comment]
Thank you, now I understand what you mean! I can of course move the canvas so that (0, 0) is at the top left. When entering the coordinates in the array, only x and y values have to be swapped.
I hope that we will then find a performant solution to draw the array on the canvas.

**Comment by AlhaririAnas** [comment]
You're welcome! 😄  I'm glad you found the explanation helpful. Moving the canvas so that (0, 0) is at the top left and swapping the x and y values when entering coordinates in the array sounds like a reasonable approach. I hope too that we'll find an efficient solution to draw the array on the canvas.
